### ISSUE TITLE
Ошибка при оплате и пополнениями десятичными значениями.

### ISSUE THREAD

**Issue by LeeGeller** [LeeGeller/Team_Project#14]
# Описание:
Если оплата проходит с десятичными значениями (50,5 рублей), тест падает.

# Локация дефекта:
https://github.com/LeeGeller/Team_Project/blob/fd83a15943b9e79cbea7b700f4ee0949e7dcc803/src/main/java/org/netology/CreditAccount.java#L8C1-L8C1

Вся программа

# Шаги воспроизведения:

1. Открыть [код тестировщика] (https://github.com/LeeGeller/Team_Project/blob/credit/src/test/java/org/netology/CreditAccountTest.java) в IDEA.
2. Запустить тест checkBalanceWhenPayDouble.
3. Посмотреть на вывод в консоли.

*Ожидаемый результат:* оплата проходит.
*Фактический результат:* incompatible types: possible lossy conversion from double to int.

*Скриншот:*
![image](https://github.com/LeeGeller/Team_Project/assets/108188624/3494dae0-0bac-42ab-adca-c42b14c85bd9)

# Окружение:
**Операционная система:** Windows 10 Pro
**IDE:** IntelliJ IDEA Community Edition 2022.3.2
**Java:** OpenJDK 11

**Comment by FedVas** [comment]
Что бы исправить этот баг ,нужно поменять тип переменной balance с int на double. А по заданию нельзя менять никакие классы кроме SavingAccounts и CreditAccounts

**Comment by FedVas** [comment]
Что бы исправить этот баг ,нужно поменять тип переменной balance с int на double. А по заданию нельзя менять никакие классы кроме SavingAccounts и CreditAccounts
