### ISSUE TITLE
Сервис не считает десятичные значения.

### ISSUE THREAD

**Issue by FedVas** [LeeGeller/Team_Project#16]
# Описание
Переменные balance и rate имеют тип int. Из за этого неправильно считается yearChange и вообще не принимаются десятичные значения во всем коде.

# Локализация дефекта 
https://github.com/LeeGeller/Team_Project/blob/93165c6636b348b09fefe247ac2b645fcd688e3b/src/main/java/org/netology/SavingAccount.java#L9

# Шаги воспроизведения

1.  Создать объект класса SavingAccount с начальным балансом 1150, минимальным балансом 0, максимальным балансом 5000 и ставкой 5.
2. Посчитать процент на остаток счёта через метод yearChange.
3. Сравнить результат.

*Ожидаемый результат:* Сумма за процент равна 57.5
*Фактический результат:*  Сумма за процент равна 55

# Скриншот
![image](https://github.com/LeeGeller/Team_Project/assets/131287108/d92a9cf1-4a73-4351-94be-b4bf85aed2c7)

# Окружение
* **Операционная система:** Windows 10 Pro 21H2
* **IDE:** IntelliJ IDEA 2023.1.1 (Community Edition
* **Java** OpenJDK 11

**Comment by LeeGeller** [comment]
К сожалению, по заданию нельзы трогать класс Account.
